[tools]
"http:tailwindcss" = { version = "4.1.18", url = "https://github.com/tailwindlabs/tailwindcss/releases/download/v{{version}}/tailwindcss-linux-{{arch()}}" }
just = "latest"
node = "25"
sqlite = "latest"
uv = "latest"
watchexec = "latest"

[tasks.build]
run = "just build"
